# Merged single-file version of the project (2026-03-04 15:22:31)
# This file was auto-generated by concatenating the original modules.
# Internal imports were wrapped in try/except to allow running as a single script.


##########################################################################################
# FILE: Info.py
##########################################################################################

""" ------ File Setup ------ """
# Remember to run this:
# from <SOALIB.>RigidForwardSOA import Joint, Inertia, SOABody, MultibodySystem, Simulation

""" ------ Body Setup ------ """
# *** Body Parameters ****
# klOO:     Hinge position (row vector)
# H_type:   Hinge type (string)
# m:        Mass (scalar)
# CkJk:     Inertia (row vector)
# klOC:     COM position (row vector)

# *** Create Body ***
# joint = Joint(<klOO>, <H_type>)
# inertia = Inertia(<m>, <CkJk>, <klOC>)
# body = SOABody(<joint>, <inertia>)

""" ------ Body Attributes ------ """ 
# If not specified program assumes zero column vectors
# theta0, beta0, tau, F_ext ---> column vectors

# *** Initial condition ***
# body.set_initial_theta0(<theta0>)   //   <theta0> ---> column vector
#       --->   "revx/y/z" use: theta0 = np.deg2rad(theta_x/y/z)
#       --->   "spherical" use: theta0 = q0 = sb.get_quat_from_degrees(theta_x, theta_y, theta_z)
#       --->   "free" use: theta0 = np.vstack([q0, l]), where l is the initial linear displacement (l = [l_x, l_y, l_z])
#       --->   "fixed" use: theta0 cannot be specified
# body.set_initial_beta0(<beta0>)   //   <beta0> ---> column vector 
#       --->   "revx/y/z" use: beta0 = omega_x/y/z
#       --->   "spherical" use: beta0 = np.array([omega_x, omega_y, omega_z]).reshape(3, 1)
#       --->   "free" use: beta0 = np.array([omega_x, omega_y, omega_z, v_x, v_y, v_z]), where v is the initial linear velocity (v = [v_x, v_y, v_z])
#       --->   "fixed" use: beta0 cannot be specified

# *** Forces ***
# body.set_tau(<tau>)   //   <tau> ---> column vector, np.array([<tau>]).reshape(nDOF, 1)

# body.set_F_ext(<F_ext>, <klBO>)   //   <F_ext>, <klBO> ---> lists of same length 
#       --->   F_ext is a list of column vectors (6, 1) with external forces
#       --->   klBO is a list of row vectors (1, 3) with the external forces' appliying position

""" ------ System Setup and Simulation ------ """ 
# *** Multibody System ***
# system = MultibodySystem(bodies)
#       --->   bodies = [body_1, body_2, ..., body_n], list of bodies created above (tip: b_1 and base: b_n)

# *** Simulation Setup ***
# sim = Simulation(system, tf, dt)
#       --->   system as created above
#       --->   tf, length of simulation
#       --->   dt, time step size

""" ------ Camera Settings ------ """ 
# sim.camera_speed(x)
#       --->   x, number from -1..1 defining the speed in both directions (zero if not changed)

# sim.camera_hor(x)
#       --->   x, number from 0..360 defining the camera rotation around z-axis (zero if not changed)

# sim.camera_ver(x)
#       --->   x, number from -90..90 defining the camera rotation around x-axis (20 if not changed)

""" ------ Parameter Call ------ """
# *** Parameter Call ***   //   Get parameter for each body for each time step
# sim.get_<parameter>()
#       --->   <parameter> = [state, X, pos, V, alpha, a, b]

""" ------ Animate or Render Animation ------ """
# *** Animate ***
# sim.animate()

# *** Render Animation to HTML-file ***   // <file_name>, r<file_path> ---> strings
# sim.animate(<file_name>, <file_path>)
#       --->   <file_name>, name of the render file
#       --->   <file_path>, copy the file path of the folder you want to save the HTML-file in.
#               nb! You must add the letter <r> in front of file path string as:
#               file_path = r"C:\Users\jepp6\OneDrive..."
#               Choose another folder than the GIT-Hub synchronize folder, since the file will
#               be to big and result in a "commit" error.

##########################################################################################
# FILE: SystemState.py
##########################################################################################

import numpy as np
import pandas as pd

class SystemState:
# State of system class
    def __init__(self, theta, beta, eta, eta_dot):
        # Parameters
        self.Theta = theta
        self.Beta = beta
        self.Eta = eta
        self.Eta_dot = eta_dot

    # Packing of state, S: Four lists to column vector
    def pack(self):
        return np.vstack([*self.Theta, *self.Beta, *self.Eta, *self.Eta_dot]).flatten()

    # Unpacking of state, S: Column vector to two lists
    @staticmethod
    def unpack(S, joints, flexs):
        S = S.flatten()
        Theta, Beta, Eta, Eta_dot = [], [], [], []
        idx = 0

        for k in joints:
            sz = k.theta_size()
            Theta.append(S[idx:idx + sz].reshape(sz, 1))
            idx += sz

        for k in joints:
            sz = k.beta_size()
            Beta.append(S[idx:idx + sz].reshape(sz, 1))
            idx += sz

        for k in flexs:
            sz = k.n_md
            Eta.append(S[idx:idx + sz].reshape(sz, 1))
            idx += sz
        
        for k in flexs:
            sz = k.n_md
            Eta_dot.append(S[idx:idx + sz].reshape(sz, 1))
            idx += sz

        return SystemState(Theta, Beta, Eta, Eta_dot)

##########################################################################################
# FILE: Body_Properties.py
##########################################################################################

import numpy as np
import scipy as sp
import scipy.linalg as la
from SOALIB import soalib as sb

class Joint:
# Joint class with H_type, H and klOO
    def __init__(self, L, H_type: str):
        # Parameters
        self.type = H_type
        self.H = sb.hinge_map(H_type)
        self.L = L
        self.klOO = np.array([L, 0, 0]).reshape(3, 1)

    # Unpacking size
    def theta_size(self):
        return {
            "revx": 1,
            "revy": 1,
            "revz": 1,
            "spherical": 4,
            "free": 7,
            "fixed": 0
        }[self.type]

    def beta_size(self):
        return {
            "revx": 1,
            "revy": 1,
            "revz": 1,
            "spherical": 3,
            "free": 6,
            "fixed": 0
        }[self.type]

class Rigid_Properties:
# Inertia class with m, CkJk and klOC
    def __init__(self, rho, klOC, w, h):
        # Parameters
        self.rho = rho
        self.klOC = klOC.reshape(3, 1)
        self.CkJk = [None]
        self.Mk = [None]
        self.w = w
        self.h = h
        self.L = [None]
    
    def get_Mk(self, m, CkJk):
        klOC = self.klOC
        CkJk = self.CkJk

        # Rigid spatial inertia
        MC = np.block([
            [np.diag(CkJk), np.zeros((3, 3))],
            [np.zeros((3, 3)), m * np.eye(3)]
        ])
        return sb.phi(klOC) @ MC @ sb.phi(klOC).T


class Flex_Properties:
    def __init__(self, E, G, n_nd, n_md):
        self.E = E
        self.G = G
        self.n_nd = n_nd
        self.n_md = n_md
        self.n_elem = self.n_nd - 1
        self.K_fl = [None]
        self.M_fl = [None]
        self.eigval = [None]
        self.PI = [None]
        self.PI_end = [None]
        self.p_1 = None
        self.F_1 = None
        self.CkJk_1 = None
        self.CkJk_2 = None
    
    def b_fl_point_mass(self, eta, eta_dot, V_r, m):
        #Point-mass-node b_fl using modal integrals (Appendix E.3.1).
        #Returns: (n_md + 6, 1) = [b_eta; b_omega; b_v]
        nmd = self.n_md

        # modal integrals
        p1 = self.p_1          # (3, nmd)
        F1 = self.F_1          # (3*nmd, nmd)
        J1 = self.CkJk_1       # (3, 3*nmd)
        J2 = self.CkJk_2       # (3*nmd, 3*nmd)

        omega = V_r[0:3, :]
        v     = V_r[3:6, :]

        # helper: X(r,eta) = sum_s J2(r,s) * eta_s   (E.3.4)
        def X_r(r):
            X = np.zeros((3, 3))
            for s in range(nmd):
                X += J2[3*r:3*r+3, 3*s:3*s+3] * float(eta[s, 0])
            return X

        # ---- b_eta (E.3.3)
        b_eta = np.zeros((nmd, 1))
        for r in range(nmd):
            p1_r = p1[:, r:r+1]                    # (3,1)
            F1_r = F1[3*r:3*r+3, :]                # (3,nmd)
            J1_r = J1[:, 3*r:3*r+3]                # (3,3)
            A_r  = J1_r + X_r(r)

            term = (
            m * sb.skew(p1_r) @ v
            + 2.0 * (F1_r @ eta_dot)
            + (A_r @ omega)
            )
            b_eta[r, 0] = -(omega.T @ term).item()

        # ---- rigid part (E.3.5)
        # use rigid/rigid 6x6 block of the flexible mass matrix (more consistent than rigid.Mk here)
        Mrr = self.M_fl[-6:, -6:]               # (6,6)

        b_rigid = sb.bar6(V_r) @ Mrr @ V_r        # V M V term in E.3.5

        p1dot_sum = p1 @ eta_dot                  # sum_r p1(r)*eta_dot_r  (3,1)

        b_omega_add = np.zeros((3, 1))
        for r in range(nmd):
            J1_r = J1[:, 3*r:3*r+3]
            A_r  = J1_r + X_r(r)
            b_omega_add += (A_r + A_r.T) @ (float(eta_dot[r, 0]) * omega)

        b_omega = b_omega_add -m * sb.skew(v) @ p1dot_sum 
        b_v_add =  m * sb.skew(omega) @ p1dot_sum

        b_rigid += np.vstack([b_omega, b_v_add])

        return np.vstack([b_eta, b_rigid])

    def set_PI(self, PI):
        self.PI = PI
    
    def set_K_fl(self, K_fl):
        self.K_fl = K_fl

    def set_M_fl(self, M_fl):
        self.M_fl = M_fl


##########################################################################################
# FILE: Structural_Analysis_PM_Rect.py
##########################################################################################

import numpy as np
import scipy.linalg as la
import pandas as pd
from SOALIB import soalib as sb


class Structural_Analysis_PM_Rect:
    """
    Class:
    Structural analysis of 3D rectangular cantilever beam with point mass assumption.

    Call:
    Structural_Analysis_PM_Rect(klOO, rho, E, G, n_nd, n_md)

    Constraint:
    Width, w >= Height, h
    """

    def get_stiff_mat_rect_3D(self):
        # b < a // h < w, w = y, h = z
        # Parameters
        w = self.w
        h = self.h
        a = w / 2
        b = h / 2
        L = self.L_elem
        E = self.E
        G = self.G

        # Book -> code
        # x -> z
        # y -> x
        # z -> y

        # Rectangular cross-section
        k_y = 1.2
        k_z = k_y
        K = a * b**3 * (16/3 - 3.36 * a / b * (1 - a**4 / (12 * b**4)))
        A = self.A
        I_y = w * h**3 / 12
        I_z = h * w**3 / 12

        # Factors
        phi_y = 12 * E * I_z * k_y / (A * G * L**2)
        phi_z = 12 * E * I_y * k_z / (A * G * L**2)
        S = G * K / L

        # X
        X = A * E / L

        # Y
        Y_1 = 12 * E * I_z / ((1 + phi_y) * L**3)
        Y_2 = 6 * E * I_z / ((1 + phi_y) * L**2)
        Y_3 = (4 + phi_y) * E * I_z / ((1 + phi_y) * L)
        Y_4 = (2 - phi_y) * E * I_z / ((1 + phi_y) * L)

        # Z
        Z_1 = 12 * E * I_y / ((1 + phi_z) * L**3)
        Z_2 = 6 * E * I_y / ((1 + phi_z) * L**2)
        Z_3 = (4 + phi_z) * E * I_y / ((1 + phi_z) * L)
        Z_4 = (2 - phi_z) * E * I_y / ((1 + phi_z) * L)

        # Stiffness matrix
        diag = [None] * 6

        diag[0] = np.array(
            [X, Y_1, Z_1, S, Z_3, Y_3, X, Y_1, Z_1, S, Z_3, Y_3])
        diag[1] = np.array([0, 0, -Z_2, 0, 0, -Y_2, 0, 0, Z_2, 0])
        diag[2] = np.array([0, Y_2, 0, 0, Z_2, 0, 0, -Y_2])
        diag[3] = np.array([-X, -Y_1, -Z_1, -S, Z_4, Y_4])
        diag[4] = np.array([0, 0, -Z_2, 0])
        diag[5] = np.array([0, Y_2])

        k = np.diag(diag[0], k=0)

        for i in range(1, 6):
            k = k + np.diag(diag[i], k=-2*i) + np.diag(diag[i], k=2*i)

        # Change so rotations first is along
        perm = [3, 4, 5, 0, 1, 2, 9, 10, 11, 6, 7, 8]

        k_perm = k[np.ix_(perm, perm)]

        return k_perm

    def get_K_st(self):

        # Get nodal stiffness
        k = self.get_stiff_mat_rect_3D()

        # Global stiffness matrix setup
        K_st = np.zeros((6*self.n_nd, 6*self.n_nd))

        for i in range(self.n_nd - 1):
            k_i = np.zeros((6*self.n_nd, 6*self.n_nd))
            k_i[i*6:i*6+12, i*6:i*6+12] = k
            K_st = K_st + k_i

        return K_st

    def get_M_nd(self):
        # Nodal masses
        m_e = self.m_e

        m = np.full(self.n_nd, m_e)
        m[-1], m[0] = m_e / 2, m_e / 2

        # Store nodal masses and lenghts
        self.m_nd = m

        block = []
        for i in range(self.n_nd):
            block.append(np.zeros((3, 3)))
            block.append(m[i] * np.eye(3, 3))

        M = la.block_diag(*block)

        return M

    def get_PI(self):

        M = self.M_nd
        K = self.K_st
        # Indexing B(boundary) I(interior) Follows Adams flex notation
        boundary_nodes = [0]          # Cantilever beam
        B = []
        for i in boundary_nodes:
            B.extend(range(6*i, 6*i+6))
        
        all_dofs = list(range(6*self.n_nd))
        I = [k for k in all_dofs if k not in B]
        K_BB = K[np.ix_(B, B)]
        K_BI = K[np.ix_(B, I)]
        K_IB = K[np.ix_(I, B)]
        K_II = K[np.ix_(I, I)]
        M_II = M[np.ix_(I, I)]

        # We compute constraint modes from static deformation shape
        Pi_b=-la.solve(K_II,K_IB)

        # Solve eigenvalue problem for Pi_t (Mass normalized!)
        eig_e, PI_e = la.eigh(K_II, M_II, subset_by_index=(0, self.n_md - 1))

        # Store eigen values

        PI_c = np.block([
        [PI_e, Pi_b],
        [np.zeros((6, self.n_md)), np.eye(6)]])

        M_n=PI_c.T @ M @ PI_c
        K_n=PI_c.T @ K @ PI_c

        eigval, PI_n = la.eigh(K_n, M_n) #, subset_by_index=(0, self.n_md - 1)

        self.eigval = eigval
        PI=PI_c@PI_n

    def get_K_fl(self):
        # Initialize K
        K = np.zeros((self.n_md + 6, self.n_md + 6))
        K[0:self.n_md, 0:self.n_md] = self.PI.T @ self.K_st @ self.PI

        return K

    def get_Modal_Int(self):
        # Parameters
        m = self.m
        m_nd = self.m_nd.reshape(-1, 1)
        L_elem = self.L_elem
        PI_t = self.PI_t
        n_md = self.n_md
        n_nd = self.n_nd

        # Initialize sums
        p_0_sum = np.zeros((3, 1))
        p_1_sum = np.zeros((3, n_md))
        CkJk_0_sum = np.zeros((3, 3))
        CkJk_1_sum = np.zeros((3, 3*n_md))
        CkJk_2_sum = np.zeros((3*n_md, 3*n_md))
        F_0_sum = np.zeros((3, n_md))
        F_1_sum = np.zeros((3*n_md, n_md))
        G_0_sum = np.zeros((n_md, n_md))
        E_0_sum = np.zeros((3, n_md))

        for i in range(n_nd):
            # Parameters
            klkO = np.array([i * L_elem, 0, 0]).reshape(3, 1)
            klkO_skew = sb.skew(klkO)

            # Compute sums
            p_0_sum += m_nd[i] * klkO

            CkJk_0_sum += - m_nd[i] * klkO_skew @ klkO_skew

            for r in range(n_md):
                F_0_sum[:, r] += m_nd[i] * \
                    klkO_skew @ PI_t[i * 3: i * 3 + 3, r]
                E_0_sum[:, r] += m_nd[i] * PI_t[i * 3: i*3 + 3, r]
                p_1_sum[:, r] += m_nd[i] * PI_t[i * 3: i*3 + 3, r]
                CkJk_1_sum[:, 3 * r: 3 * r + 3] += m_nd[i] * \
                    sb.skew(PI_t[i * 3: i*3 + 3, r]) @ klkO_skew
                for s in range(n_md):
                    G_0_sum[r, s] += m_nd[i] * PI_t[i * 3: i *
                                                    3 + 3, r].T @ PI_t[i * 3: i*3 + 3, s]
                    CkJk_2_sum[3*r:3*r+3, 3*s:3*s+3] += m_nd[i] * sb.skew(PI_t[i * 3: i *
                                                                               3 + 3, r]) @ sb.skew(PI_t[i * 3: i*3 + 3, s])
                    F_1_sum[3*r:3*r+3, s] += m_nd[i] * sb.skew(PI_t[i * 3: i *
                                                                    3 + 3, r]) @ PI_t[i * 3: i*3 + 3, s]

        # Store modal integrals
        self.p_0 = 1/m * p_0_sum
        self.p_1 = 1/m * p_1_sum
        self.CkJk_0 = CkJk_0_sum
        self.CkJk_0[0, 0] = self.CkJk[0]
        self.CkJk_1 = - CkJk_1_sum
        self.CkJk_2 = - CkJk_2_sum
        self.F_0 = F_0_sum
        self.F_1 = - F_1_sum
        self.G_0 = G_0_sum
        self.E_0 = E_0_sum

    def get_M_fl(self):
        # Collect modal integrals
        self.get_Modal_Int()

        # Parameters
        p_0_skew = sb.skew(self.p_0)
        CkJk_0 = self.CkJk_0
        F_0 = self.F_0
        G_0 = self.G_0
        E_0 = self.E_0

        m = self.m

        # Build M
        rw1 = np.hstack([G_0, F_0.T, E_0.T])
        rw2 = np.hstack([F_0, CkJk_0, m * p_0_skew])
        rw3 = np.hstack([E_0, -m * p_0_skew, m * np.eye(3)])

        return np.vstack([rw1, rw2, rw3])

    def __init__(self, rigid: Rigid_Properties, flex: Flex_Properties):
        self.w = rigid.w
        self.h = rigid.h
        self.L = rigid.L
        self.A = rigid.w * rigid.h
        self.m = rigid.rho * self.A * self.L
        self.E = flex.E
        self.G = flex.G
        self.n_nd = flex.n_nd
        self.n_md = flex.n_md
        self.CkJk = rigid.CkJk
        self.n_elem = self.n_nd - 1
        self.L_elem = self.L / self.n_elem
        self.m_e = rigid.rho * self.A * self.L_elem

        # Structural analysis
        self.K_st = self.get_K_st()
        self.M_nd = self.get_M_nd()
        self.PI = self.get_PI()
        self.K_fl = self.get_K_fl()
        self.M_fl = self.get_M_fl()

##########################################################################################
# FILE: SOABody.py
##########################################################################################

import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
from SOALIB import soalib as sb
from scipy.integrate import solve_ivp
import pandas as pd

# Increase limit to 100 MB (default is 20)
plt.rcParams['animation.embed_limit'] = 1000


class SOABody:
    # SOAbody class
    class Force:
        def __init__(self, joint: Joint):
            self.tau = np.zeros((joint.beta_size(), 1))
            self.F_ext = np.zeros((6, 1))

    class InitialCondition:
        def __init__(self, joint: Joint, flex: Flex_Properties):
            # Setup of initial conditions (assumes identity rotation and no initial velocity)
            self.theta0 = np.zeros((joint.theta_size(), 1))
            if np.size(self.theta0) == 4:
                self.theta0[-1] = 1
            elif np.size(self.theta0) == 7:
                self.theta0[3] = 1
            self.beta0 = np.zeros((joint.beta_size(), 1))

            # Setup of initial conditions for eta and eta_dot
            self.eta0 = np.zeros((flex.n_md, 1))
            self.eta_dot0 = np.zeros((flex.n_md, 1))

    def __init__(self, joint: Joint, rigid: Rigid_Properties, flex: Flex_Properties):
        # Import classes
        self.joint = joint
        self.rigid = rigid
        self.flex = flex
        self.force = self.Force(self.joint)
        self.initialcondition = self.InitialCondition(joint, flex)
        rigid.A = rigid.h * rigid.w
        rigid.L = joint.L
        flex.L_elem = joint.L / flex.n_elem
        self.m = rigid.rho * rigid.A * joint.L
        self.rigid.CkJk = np.array([1/12 * self.m * (rigid.h**2 + rigid.w**2), 1/12 * self.m * (
            rigid.h**2 + joint.L**2), 1/12 * self.m * (rigid.w**2 + joint.L**2)])
        rigid.Mk = rigid.get_Mk(self.m, self.rigid.CkJk)

        # Structural analysis is PI == [None] (Point mass: Rectangular cross section)
        if self.flex.PI == [None]:
            body_analysis = Structural_Analysis_PM_Rect(rigid, flex)
            """
            print("p_0")
            print(pd.DataFrame(body_analysis.p_0))
            print("p_1")
            print(pd.DataFrame(body_analysis.p_1))
            print("CkJk_0")
            print(pd.DataFrame(body_analysis.CkJk_0))
            print("CkJk_1")
            print(pd.DataFrame(body_analysis.CkJk_1))
            print("CkJk_2")
            print(pd.DataFrame(body_analysis.CkJk_2))
            print("F_0")
            print(pd.DataFrame(body_analysis.F_0))
            print("F_1")
            print(pd.DataFrame(body_analysis.F_1))
            print("G_0")
            print(pd.DataFrame(body_analysis.G_0))
            print("E_0")
            print(pd.DataFrame(body_analysis.E_0))
            print("eig")
            print(pd.DataFrame(body_analysis.eigval))
            print("PI_t")
            print(pd.DataFrame(body_analysis.PI_t))
            print("K_st")
            print(pd.DataFrame(body_analysis.K_st))
            """
            # PI
            self.flex.PI = body_analysis.PI
            self.flex.PI_end = body_analysis.PI[-6:, :]
            self.flex.eigval = body_analysis.eigval

            # Stiffness and mass matrix
            self.flex.K_fl = body_analysis.K_fl
            self.flex.M_fl = body_analysis.M_fl

            n = self.flex.n_md
            eig = np.array(self.flex.eigval).reshape(-1)      # should be ω^2
            omega = np.sqrt(eig[:n])                          # ω

            zeta = 0.02 * np.ones(n)                          # e.g. 2% for all modes

            C_eta = np.diag(2.0 * zeta * omega)               # (n×n)

            C_fl = np.zeros_like(self.flex.M_fl)              # (n+6 × n+6)
            C_fl[:n, :n] = C_eta
            self.flex.C_fl = C_fl

            # Modal integral for gyroscopic force
            self.flex.p_1 = body_analysis.p_1
            self.flex.F_1 = body_analysis.F_1
            self.flex.CkJk_1 = body_analysis.CkJk_1
            self.flex.CkJk_2 = body_analysis.CkJk_2

        # D_m invers (offline)
        H_M_fl = np.hstack(
            [np.eye(self.flex.n_md, self.flex.n_md), np.zeros((self.flex.n_md, 6))])
        A_fl = sb.get_A(self.flex.PI_end, self.joint.klOO)
        self.flex.L_fl = la.inv(H_M_fl @ self.flex.M_fl @ H_M_fl.T)
        zeta = H_M_fl @ A_fl
        self.flex.U_fl = self.flex.L_fl @ zeta
        self.flex.D_fl = zeta.T @ self.flex.U_fl

    def set_tau(self, tau):
        self.force.tau = tau

    def set_F_ext(self, F_ext):
        self.force.F_ext = F_ext

    def set_initial_theta0(self, theta0):
        self.initialcondition.theta0 = theta0

    def set_initial_beta0(self, beta0):
        self.initialcondition.beta0 = beta0

    def get_D_m_inv(self, Gamma, x):
        # Calculate D_m_inv
        if x == 0:
            Dminv = self.flex.L_fl
        elif x == 1:
            Gamma_inv = la.inv(Gamma)
            Dminv = self.flex.L_fl - \
                la.solve((Gamma_inv + self.flex.D_fl).T,
                         self.flex.U_fl.T).T @ self.flex.U_fl.T
        return Dminv

##########################################################################################
# FILE: ATBI_Flex.py
##########################################################################################

import numpy as np
import scipy.linalg as la
from SOALIB import soalib as sb
import pandas as pd


class ATBI_Flex:
    # ATBI class with bodies
    def __init__(self, bodies):
        # Parameters
        self.bodies = bodies
        self.n = len(bodies)

    def coriolis(self, V, beta, H):
        deltaV = H.T @ beta
        return sb.skew6(V) @ deltaV - sb.bar6(deltaV) @ deltaV

    def gyroscopic(self, V, M):
        return sb.bar6(V) @ M @ V

    def theta2X(self, theta, joint_type, klOO):
        if joint_type == "revx":
            ang = theta.item()
            q = np.array([[np.sin(ang/2)], [0], [0], [np.cos(ang/2)]])
            return np.vstack((q, klOO)), q

        elif joint_type == "revy":
            ang = theta.item()
            q = np.array([[0], [np.sin(ang/2)], [0], [np.cos(ang/2)]])
            return np.vstack((q, klOO)), q

        elif joint_type == "revz":
            ang = theta.item()
            q = np.array([[0], [0], [np.sin(ang/2)], [np.cos(ang/2)]])
            return np.vstack((q, klOO)), q

        elif joint_type == "spherical":
            q = theta.reshape(4, 1)
            q = q / np.linalg.norm(q)
            return np.vstack((q, klOO)), q

        elif joint_type == "free":
            q = theta[0:4].reshape(4, 1)
            v = theta[4:7].reshape(3, 1)
            return np.vstack((q, klOO)), q

        elif joint_type == "fixed":
            q = np.array([[0], [0], [0], [1]])
            return np.vstack((q, klOO)), q

    def scatter_kinematics(self, state: SystemState):

        # Number of bodies
        n = len(self.bodies)

        # Set up lists
        X = [None] * n
        V = [None] * n
        A_fl = [None] * n
        V_f = [None] * n
        V_r = [None] * n
        a_fl = [None] * n
        b_fl = [None] * n

        for k in reversed(range(n)):
            # Parameters of the body
            body = self.bodies[k]
            theta = state.Theta[k]
            beta = state.Beta[k]
            eta_dot = state.Eta_dot[k]
            H = body.joint.H
            Mk = body.rigid.Mk
            PI = body.flex.PI_end
            n_md = body.flex.n_md

            # Build X
            X[k], q = self.theta2X(theta, body.joint.type, body.joint.klOO)

            # Build A: NB! Typo in text?!?!
            R3 = sb.q2R(q.flatten(), 3)
            A_fl[k] = sb.get_A(PI, R3.T @ X[k][4:7])

            if k == n - 1:
                V_f[k] = eta_dot
                V_r[k] = H.T @ beta
            else:
                R6 = sb.q2R(q.flatten(), 6)
                R_tot = sb.get_R_tot(R6, n_md)

                V_f[k] = eta_dot
                V_r[k] = A_fl[k+1].T @ R_tot.T @ V[k+1] + H.T @ beta

            a_fl[k] = np.vstack(
                [np.zeros((n_md, 1)), self.coriolis(V_r[k], beta, H)])
            eta = state.Eta[k]              # you MUST pull eta too (E.3.4 needs it)
            b_fl[k] = body.flex.b_fl_point_mass(eta, eta_dot, V_r[k], body.m)

            V[k] = np.vstack([V_f[k], V_r[k]])

        return X, V, a_fl, b_fl

    def gather_ATBI(self, state: SystemState, a_fl, b_fl, X, t):
        # Step 3 of ATBI (gather sweep): Takes generalized forces, Coriolis-, gyroscopic
        # terms, X-vector and system configuration and returns G and nu parameters

        # Number of bodies
        n = len(self.bodies)

        # Setup lists
        P_pr_plus = [None] * n
        D_m = [None] * n
        g_fl = [None] * n
        P_pr = [None] * n
        D_pr = [None] * n
        G_pr = [None] * n
        nu_m = [None] * n
        nu_pr = [None] * n
        z_pr_plus = [None] * n

        for k in range(n):
            # Parameters of the body
            body = self.bodies[k]
            H_B = body.joint.H
            F_ext = body.force.F_ext
            tau_pr = body.force.tau
            eta = state.Eta[k]
            eta_dot = state.Eta_dot[k]
            C_fl = body.flex.C_fl
            M_fl = body.flex.M_fl
            K_fl = body.flex.K_fl
            PI = body.flex.PI_end
            n_md = body.flex.n_md
            H_M_fl = np.hstack([np.eye(n_md, n_md), np.zeros((n_md, 6))])
            klOO = X[k][4:7]

            # External force
            t0 = 0.01
            sigma = 0.01

            scale = np.exp(-((t - t0)**2)/(2*sigma**2))

            F_ext_term = scale * np.vstack([PI.T @ F_ext, sb.phi(klOO) @ F_ext])

            """
            if t <= 0.25:
                F_ext_term = np.vstack([PI.T @ F_ext, sb.phi(klOO) @ F_ext])
            """

            if k == 0:
                # Gather loop for k = 0 (Base Case)
                # 13.6
                Gamma_fl = np.zeros((0, 6))
                P_fl = M_fl
                D_m[k] = H_M_fl @ P_fl @ H_M_fl.T
                mu_fl = P_fl[-6:, :] @ H_M_fl.T
                D_m_inv = body.get_D_m_inv(Gamma_fl, 0)
                g_fl[k] = mu_fl @ D_m_inv
                P_pr[k] = P_fl[-6:, -6:] - g_fl[k] @ mu_fl.T
                D_pr[k] = H_B @ P_pr[k] @ H_B.T
                G_pr[k] = P_pr[k] @ la.solve(D_pr[k].T, H_B).T
                tau_pr_bar = np.eye(6, 6) - G_pr[k] @ H_B
                P_pr_plus[k] = tau_pr_bar @ P_pr[k]

                # 13.7
                z = b_fl[k] + K_fl @ np.vstack([eta, np.zeros((6, 1))]) - F_ext_term + C_fl @ np.vstack([eta_dot, np.zeros((6, 1))])
                eps_m = - z[0:n_md]  # tau_m (assumed to be zero): dim(n_md, 1)
                nu_m[k] = D_m_inv @ eps_m

                z_pr = z[-6:] + g_fl[k] @ eps_m + P_pr[k] @ a_fl[k][-6:]
                eps_pr = tau_pr - H_B @ z_pr
                nu_pr[k] = la.solve(D_pr[k], eps_pr)
                z_pr_plus[k] = z_pr + G_pr[k] @ eps_pr

            else:
                # 13.6
                # Unpacking X-vector
                q = X[k-1][0:4]

                # Rotation
                R6 = sb.q2R(q.flatten(), 6)

                A_fl = sb.get_A(PI, klOO)

                # Gather loop for k > 0
                Gamma_fl = R6 @ P_pr_plus[k-1] @ R6.T  # ?!?!?!?
                P_fl = A_fl @ Gamma_fl @ A_fl.T + M_fl
                D_m[k] = H_M_fl @ P_fl @ H_M_fl.T
                mu_fl = P_fl[-6:, :] @ H_M_fl.T
                D_m_inv = body.get_D_m_inv(Gamma_fl, 1)
                g_fl[k] = mu_fl @ D_m_inv
                P_pr[k] = P_fl[-6:, -6:] - g_fl[k] @ mu_fl.T
                D_pr[k] = H_B @ P_pr[k] @ H_B.T
                G_pr[k] = P_pr[k] @ la.solve(D_pr[k].T, H_B).T
                tau_pr_bar = np.eye(6, 6) - G_pr[k] @ H_B
                P_pr_plus[k] = tau_pr_bar @ P_pr[k]

                # 13.7
                z = A_fl @ R6 @ z_pr_plus[k-1] + b_fl[k] + K_fl @ np.vstack([eta, np.zeros((6, 1))]) - F_ext_term + C_fl @ np.vstack([eta_dot, np.zeros((6, 1))])
                eps_m = - z[0:n_md]  # tau_m (assumed to be zero): dim(n_md, 1)
                nu_m[k] = D_m_inv @ eps_m

                z_pr = z[-6:] + g_fl[k] @ eps_m + P_pr[k] @ a_fl[k][-6:]
                eps_pr = tau_pr - H_B @ z_pr
                nu_pr[k] = la.solve(D_pr[k], eps_pr)
                z_pr_plus[k] = z_pr + G_pr[k] @ eps_pr

        return G_pr, nu_pr, nu_m, g_fl

    def scatter_ATBI(self, a_fl, X, G_pr, nu_pr, nu_m, g_fl):
        # Step 4 of ATBI (second scatter sweep): Takes Coriolis term, X-vector, G,
        # nu and hinge map, H and returns generalized acceleration, gamma

        # Number of bodies
        n = len(self.bodies)

        # Setup of list
        alpha_fl = [None] * n
        theta_ddot = [None] * n
        eta_ddot = [None] * n
        A_fl = [None] * n

        # Spatial gravity
        g = np.array([0, 0, 0, 0, 0, 9.81]).reshape(6, 1)

        # Spatial gravity rotation setup
        Ri = [None] * (n + 1)
        Ri[-1] = np.eye(6)

        # Loop backwards from n-1 down to 0
        for k in range(n - 1, -1, -1):
            # Parameters of the body
            body = self.bodies[k]
            H_B = body.joint.H
            n_md = body.flex.n_md
            PI = body.flex.PI_end

            # Unpacking rotation
            q = X[k][0:4]

            # Rotation
            R3 = sb.q2R(q.flatten(), 3)
            R6 = sb.q2R(q.flatten(), 6)

            # Spatial gravity rotation
            Ri[k] = Ri[k+1]  @ R6

            A_fl[k] = sb.get_A(PI, R3.T @ X[k][4:7])

            if k == n - 1:
                # Scatter loop (Tip of the chain)
                theta_ddot[k] = nu_pr[k]
                alpha_pr = H_B.T @ theta_ddot[k] + a_fl[k][-6:]
                eta_ddot[k] = nu_m[k] - g_fl[k].T @ alpha_pr
                alpha_fl[k] = np.vstack([eta_ddot[k], alpha_pr])

            else:
                # Scatter loop
                R_tot = sb.get_R_tot(R6, n_md)

                alpha_pr_plus = A_fl[k+1].T @ R_tot.T @ alpha_fl[k+1]
                theta_ddot[k] = nu_pr[k] - G_pr[k].T @ alpha_pr_plus
                alpha_pr = alpha_pr_plus + H_B.T @ theta_ddot[k] + a_fl[k][-6:]
                eta_ddot[k] = nu_m[k] - g_fl[k].T @ alpha_pr
                alpha_fl[k] = np.vstack([eta_ddot[k], alpha_pr])

        return theta_ddot, eta_ddot, alpha_fl

##########################################################################################
# FILE: MultibodySystem.py
##########################################################################################

import numpy as np
import pandas as pd
from SOALIB import soalib as sb

class MultibodySystem:
    def __init__(self, bodies):
        self.bodies = bodies
        self.ATBI = ATBI_Flex(bodies)
        Theta_0 = [b.initialcondition.theta0 for b in bodies]
        Beta_0 = [b.initialcondition.beta0 for b in bodies]
        Eta_0 = [b.initialcondition.eta0 for b in bodies]
        Eta_dot_0 = [b.initialcondition.eta_dot0 for b in bodies]
        self.S0 = SystemState(Theta_0, Beta_0, Eta_0, Eta_dot_0).pack()

    def EOM(self, t, S):
        state = SystemState.unpack(S.reshape(-1, 1), [b.joint for b in self.bodies], [b.flex for b in self.bodies])

        # Normalize quaternions
        for k, body in enumerate(self.bodies):
            if body.joint.type in ["spherical", "free"]:
                q = state.Theta[k][0:4]
                state.Theta[k][0:4] = q / np.linalg.norm(q)

        X, V, a_fl, b_fl = self.ATBI.scatter_kinematics(state)
        G_pr, nu_pr, nu_m, g_fl = self.ATBI.gather_ATBI(state, a_fl, b_fl, X, t)
        theta_ddot, eta_ddot, alpha_fl = self.ATBI.scatter_ATBI(a_fl, X, G_pr, nu_pr, nu_m, g_fl)

        Theta_dot, Eta_dot_list = [], []
        for k, body in enumerate(self.bodies):
            if body.joint.type.startswith("rev"):
                Theta_dot.append(state.Beta[k].reshape(1, 1))
            elif body.joint.type == "spherical":
                Theta_dot.append(sb.quat_derivative(state.Theta[k], state.Beta[k]).reshape(4, 1))
            elif body.joint.type == "free":
                qdot = sb.quat_derivative(state.Theta[k][0:4], state.Beta[k][0:3]).reshape(4, 1)
                Theta_dot.append(np.vstack([qdot, state.Beta[k][3:6]]).reshape(7, 1))
            elif body.joint.type == "fixed":
                Theta_dot.append(np.zeros((0, 1)))

            Eta_dot_list.append(state.Eta_dot[k].reshape(body.flex.n_md, 1))

        S_dot = np.vstack([*Theta_dot, *theta_ddot, *Eta_dot_list, *eta_ddot]).flatten()
        
        return S_dot

##########################################################################################
# FILE: Simulation.py
##########################################################################################

import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
from matplotlib.animation import FuncAnimation
from scipy.integrate import solve_ivp
import os
from SOALIB import soalib as sb
import pandas as pd


class Simulation:
    class Data:
        def __init__(self):
            self.time, self.state, self.X_list, self.V_list, self.a_list, self.b_list, self.alpha_list, self.pos = [
            ], [], [], [], [], [], [], []

    class Setting:
        def __init__(self):
            self.camera_speed = 0
            self.camera_ver = 20
            self.camera_hor = 0

    def __init__(self, system: MultibodySystem, tf, dt):
        self.system = system
        self.data = self.Data()
        self.setting = self.Setting()
        self.tf = tf
        self.dt = dt

        # Increase limit to 100 MB (default is 20)
        plt.rcParams['animation.embed_limit'] = 1000

    def IntegrateSystem(self):
        print("Integrating...")
        t_eval = np.linspace(0, self.tf, int(self.tf/self.dt)+1)

        sol = solve_ivp(
            fun=self.system.EOM,
            t_span=(0, self.tf),
            y0=self.system.S0,
            t_eval=t_eval,
            method="Radau",
            rtol = 1e-3,
            atol = 1e-5
        )

        print("Integration successful!")

        # Extract results to match [t, y] format
        self.data.time = sol.t
        states = sol.y.T

        # Find X-vector for each time step
        for i in range(len(self.data.time)):

            # Unpack state
            current_state = SystemState.unpack(
                states[i].reshape(-1, 1), [b.joint for b in self.system.bodies], [b.flex for b in self.system.bodies])

            # Kinematic scatter loop to find X
            X, V, a_fl, b_fl = self.system.ATBI.scatter_kinematics(
                current_state)
            G_pr, nu_pr, nu_m, g_fl = self.system.ATBI.gather_ATBI(
                current_state, a_fl, b_fl, X, self.data.time[i])
            _, _, alpha = self.system.ATBI.scatter_ATBI(
                a_fl, X, G_pr, nu_pr, nu_m, g_fl)

            # Add to list
            self.data.state.append(current_state)
            self.data.X_list.append(X)
            self.data.V_list.append(V)
            self.data.a_list.append(a_fl)
            self.data.b_list.append(b_fl)
            self.data.alpha_list.append(alpha)

    # Call functions for data
    def get_state(self):
        return self.data.state

    def get_X(self):
        return self.data.X_list

    def get_V(self):
        return self.data.V_list

    def get_a(self):
        return self.data.a_list

    def get_b(self):
        return self.data.b_list

    def get_alpha(self):
        return self.data.alpha_list

    # Settings
    def camera_speed(self, x):
        self.setting.camera_speed = x

    def camera_ver(self, x):
        self.setting.camera_ver = x

    def camera_hor(self, x):
        self.setting.camera_hor = x

    def nNodalPos(self):
        t = self.data.time
        X = self.data.X_list
        n = len(self.system.bodies)

        nt = len(t)
        nodal_pos = []

        for i in range(nt):
            # Current state
            state = self.data.state[i]

            # End node (O_-1+)
            last_end = np.zeros((3, 1))

            Ri = np.eye(3)

            nodes_i = []

            for k in range(n - 1, -1, -1):
                # Current body parameters
                eta = state.Eta[k]
                body = self.system.bodies[k]
                n_nd = body.flex.n_nd
                PI = body.flex.PI
                L_elem = body.flex.L_elem

                nodes_k = []

                # Unpancking X-vector
                q = X[i][k][0:4]    # Quaternion: k+1 to k

                # Rotation
                Ri = Ri @ sb.q2R(q.flatten(), 3)
                

                for j in range(n_nd):
                    # Undeformed position in local frame (Structural analysis assumes beam along Z-axis)
                    pos_und = np.array([[j * L_elem], [0], [0]])

                    # Translational deformation for node j
                    # (Translations are stored at indices j*6+3 to j*6+6 in the PI matrix)

                    # Check if the current time is very close to an integer
                    x = 0
                    if i % 20 == 0 and j == n_nd-1 and x == 1:
                        print(pd.DataFrame(eta))
                        print(pd.DataFrame(PI[j*6+3 : j*6+6, :]))
                        
                    u_j = PI[j*6+3: j*6+6, :] @ eta

                    # Global position of node j (of body k)
                    p_glob = last_end + Ri @ (pos_und + u_j)
                    nodes_k.append(p_glob)

                last_end = nodes_k[-1]
                nodes_i.append(nodes_k)
            
            nodal_pos.append(nodes_i)
                
        return nodal_pos

    def animate_nodes(self, filename="", save_dir=""):
        # Takes nodal position list and returns 3D simulation of the flexible beam
        
        t = self.data.time
        dt = t[1] - t[0]

        # Get nodal positions for the flexible beam
        nodal_pos = self.nNodalPos()
        
        if not nodal_pos:
            print("Error: No nodal position data found. Did you run the integration?")
            return

        nt = len(nodal_pos)
        n_bodies = len(nodal_pos[0])

        # Initialize animation
        fig = plt.figure(figsize=(10, 8))
        ax = fig.add_subplot(111, projection='3d')

        # Determine Axis Limits dynamically based on node movement
        all_points = []
        step = max(1, nt // 50)  # Sample frames to speed up boundary calculation
        for i in range(0, nt, step):
            for body_nodes in nodal_pos[i]:
                for node in body_nodes:
                    all_points.append(node.flatten())

        all_points = np.array(all_points)
        if len(all_points) > 0:
            max_range = np.abs(all_points).max()
        else:
            max_range = 1.0

        # Prevent zero-range if the beam doesn't move
        if max_range == 0:
            max_range = 1.0

        ax.set_xlim(-max_range, max_range)
        ax.set_ylim(-max_range, max_range)
        ax.set_zlim(-max_range, max_range)

        ax.set_xlabel('X')
        ax.set_ylabel('Y')
        ax.set_zlabel('Z')
        ax.set_title(f"Flexible n-Body Animation ({n_bodies} Bodies)")

        # Create n colored lines (one per flexible link)
        cmap = mpl.colormaps['tab10']
        colors = cmap(np.linspace(0, 1, n_bodies))
        lines = []

        for i in range(n_bodies):
            line, = ax.plot([], [], [], '-', lw=4, color=colors[i])
            lines.append(line)

        # Scatter plot for the nodes
        node_dots, = ax.plot([], [], [], 'ko', markersize=4)

        # Plot origin for reference
        ax.plot([0], [0], [0], 'o', color='gray', markersize=6)

        # Initialize the timer text
        time_text = ax.text2D(0.05, 0.95, '', transform=ax.transAxes)

        def update(frame_idx):
            current_state = nodal_pos[frame_idx]
            
            all_xs, all_ys, all_zs = [], [], []

            # Update each body separately
            for b_idx in range(n_bodies):
                body_nodes = current_state[b_idx]
                
                xs = [float(node[0][0]) for node in body_nodes]
                ys = [float(node[1][0]) for node in body_nodes]
                zs = [float(node[2][0]) for node in body_nodes]

                lines[b_idx].set_data(xs, ys)
                lines[b_idx].set_3d_properties(zs)
                
                all_xs.extend(xs)
                all_ys.extend(ys)
                all_zs.extend(zs)

            node_dots.set_data(all_xs, all_ys)
            node_dots.set_3d_properties(all_zs)

            # Update timer
            time_text.set_text(f'Time: {t[frame_idx]:.2f} s')

            # Handle camera rotation settings
            ax.view_init(elev=self.setting.camera_ver,
                         azim=frame_idx * self.setting.camera_speed * 40 * dt + self.setting.camera_hor)

            return (*lines, node_dots, time_text)

        # Create Animation
        anim = FuncAnimation(
            fig,
            update,
            frames=nt,
            interval=dt*1000,
            blit=False)

        if filename != "":
            print("Rendering animation to HTML... (This may take a minute)")
            filename = filename + ".html"

            if save_dir:
                os.makedirs(save_dir, exist_ok=True)
                fullpath = os.path.join(save_dir, filename)
            else:
                fullpath = filename

            with open(fullpath, "w") as f:
                f.write(anim.to_jshtml())

            print("Rendering of animation: Done!")
            print(f"Saved to {fullpath}")

        else:
            plt.show()
    
    def get_pos(self):
        self.data.pos = self.nBodyPos()
        return self.data.pos

##########################################################################################
# FILE: TestFlex.py
##########################################################################################

import numpy as np
from SOALIB import soalib as sb
import pandas as pd

L = 1
H_type1 = "revy"
# revy and force in y works
klOC = np.array([L/2, 0, 0])

# n_md_max = (n_nd - 1) * 3

E, G, rho, n_nd, n_md = 2.1e11, 8e10, 7850, 5, 3

w, h = 0.04, 0.04

j1 = Joint(L, H_type1)
r = Rigid_Properties(rho, klOC, w, h)
f = Flex_Properties(E, G, n_nd, n_md)
b1 = SOABody(j1, r, f)

PIe = b1.flex.PI_end

print(np.linalg.norm(PIe[3, :]))
print(np.linalg.norm(PIe[4, :]))
print(np.linalg.norm(PIe[5, :]))

K = b1.flex.K_fl
M = b1.flex.M_fl
print(pd.DataFrame(M[-6:, -6:]))

F_ext = np.array([0, 0, 0, 0, -1e5,0]).reshape(6, 1)
b1.set_F_ext(F_ext)
#b1.set_initial_beta0(-100)
bodies = [b1]

system = MultibodySystem(bodies)

tf = 3
dt = 0.01

sim = Simulation(system, tf, dt)

sim.camera_speed(0)
sim.camera_ver(45)
sim.camera_hor(45)

sim.IntegrateSystem()

#save_dir = r"C:\Users\jepp6\OneDrive - Aarhus universitet\Dokumenter\Noter\6. Semester\Bachelor Projekt\BachelorCode\Renders"

sim.animate_nodes()


"""
print("PI")
print(pd.DataFrame(b1.flex.PI))
print("eigval")
print(pd.DataFrame(b1.flex.eigval))
print("K_fl")
print(pd.DataFrame(b1.flex.K_fl))
print("M_fl_red")
print(pd.DataFrame(b1.flex.M_fl[-6:, -6:]))
print("M_fl")
print(pd.DataFrame(b1.flex.M_fl))
"""

# q norm