"""
Single-file merge of the SOA-flex Python modules.

This file was auto-generated by concatenating the original project files with only minimal edits
(mainly: removing intra-project imports, and wrapping the TestFlex script in a __main__ guard).

Original files merged (in order):
  - Info.py
  - Body_Properties.py
  - Structural_Analysis_PM_Rect.py
  - SystemState.py
  - ATBI_Flex.py
  - MultibodySystem.py
  - Simulation.py
  - SOABody.py
  - TestFlex.py
"""


# ==============================================================================
# BEGIN Info.py
# ==============================================================================

""" ------ File Setup ------ """
# Remember to run this:
# from <SOALIB.>RigidForwardSOA import Joint, Inertia, SOABody, MultibodySystem, Simulation

""" ------ Body Setup ------ """
# *** Body Parameters ****
# klOO:     Hinge position (row vector)
# H_type:   Hinge type (string)
# m:        Mass (scalar)
# CkJk:     Inertia (row vector)
# klOC:     COM position (row vector)

# *** Create Body ***
# joint = Joint(<klOO>, <H_type>)
# inertia = Inertia(<m>, <CkJk>, <klOC>)
# body = SOABody(<joint>, <inertia>)

""" ------ Body Attributes ------ """ 
# If not specified program assumes zero column vectors
# theta0, beta0, tau, F_ext ---> column vectors

# *** Initial condition ***
# body.set_initial_theta0(<theta0>)   //   <theta0> ---> column vector
#       --->   "revx/y/z" use: theta0 = np.deg2rad(theta_x/y/z)
#       --->   "spherical" use: theta0 = q0 = sb.get_quat_from_degrees(theta_x, theta_y, theta_z)
#       --->   "free" use: theta0 = np.vstack([q0, l]), where l is the initial linear displacement (l = [l_x, l_y, l_z])
#       --->   "fixed" use: theta0 cannot be specified
# body.set_initial_beta0(<beta0>)   //   <beta0> ---> column vector 
#       --->   "revx/y/z" use: beta0 = omega_x/y/z
#       --->   "spherical" use: beta0 = np.array([omega_x, omega_y, omega_z]).reshape(3, 1)
#       --->   "free" use: beta0 = np.array([omega_x, omega_y, omega_z, v_x, v_y, v_z]), where v is the initial linear velocity (v = [v_x, v_y, v_z])
#       --->   "fixed" use: beta0 cannot be specified

# *** Forces ***
# body.set_tau(<tau>)   //   <tau> ---> column vector, np.array([<tau>]).reshape(nDOF, 1)

# body.set_F_ext(<F_ext>, <klBO>)   //   <F_ext>, <klBO> ---> lists of same length 
#       --->   F_ext is a list of column vectors (6, 1) with external forces
#       --->   klBO is a list of row vectors (1, 3) with the external forces' appliying position

""" ------ System Setup and Simulation ------ """ 
# *** Multibody System ***
# system = MultibodySystem(bodies)
#       --->   bodies = [body_1, body_2, ..., body_n], list of bodies created above (tip: b_1 and base: b_n)

# *** Simulation Setup ***
# sim = Simulation(system, tf, dt)
#       --->   system as created above
#       --->   tf, length of simulation
#       --->   dt, time step size

""" ------ Camera Settings ------ """ 
# sim.camera_speed(x)
#       --->   x, number from -1..1 defining the speed in both directions (zero if not changed)

# sim.camera_hor(x)
#       --->   x, number from 0..360 defining the camera rotation around z-axis (zero if not changed)

# sim.camera_ver(x)
#       --->   x, number from -90..90 defining the camera rotation around x-axis (20 if not changed)

""" ------ Parameter Call ------ """
# *** Parameter Call ***   //   Get parameter for each body for each time step
# sim.get_<parameter>()
#       --->   <parameter> = [state, X, pos, V, alpha, a, b]

""" ------ Animate or Render Animation ------ """
# *** Animate ***
# sim.animate()

# *** Render Animation to HTML-file ***   // <file_name>, r<file_path> ---> strings
# sim.animate(<file_name>, <file_path>)
#       --->   <file_name>, name of the render file
#       --->   <file_path>, copy the file path of the folder you want to save the HTML-file in.
#               nb! You must add the letter <r> in front of file path string as:
#               file_path = r"C:\Users\jepp6\OneDrive..."
#               Choose another folder than the GIT-Hub synchronize folder, since the file will
#               be to big and result in a "commit" error.

# END Info.py


# ==============================================================================
# BEGIN Body_Properties.py
# ==============================================================================

import numpy as np
import scipy as sp
import scipy.linalg as la
from SOALIB import soalib as sb

class Joint:
# Joint class with H_type, H and klOO
    def __init__(self, L, H_type: str):
        # Parameters
        self.type = H_type
        self.H = sb.hinge_map(H_type)
        self.L = L
        self.klOO = np.array([L, 0, 0]).reshape(3, 1)

    # Unpacking size
    def theta_size(self):
        return {
            "revx": 1,
            "revy": 1,
            "revz": 1,
            "spherical": 4,
            "free": 7,
            "fixed": 0
        }[self.type]

    def beta_size(self):
        return {
            "revx": 1,
            "revy": 1,
            "revz": 1,
            "spherical": 3,
            "free": 6,
            "fixed": 0
        }[self.type]

class Rigid_Properties:
# Inertia class with m, CkJk and klOC
    def __init__(self, rho, klOC, w, h):
        # Parameters
        self.rho = rho
        self.klOC = klOC.reshape(3, 1)
        self.CkJk = [None]
        self.Mk = [None]
        self.w = w
        self.h = h
        self.L = [None]
    
    def get_Mk(self, m, CkJk):
        klOC = self.klOC
        CkJk = self.CkJk

        # Rigid spatial inertia
        MC = np.block([
            [np.diag(CkJk), np.zeros((3, 3))],
            [np.zeros((3, 3)), m * np.eye(3)]
        ])
        return sb.phi(klOC) @ MC @ sb.phi(klOC).T


class Flex_Properties:
    def __init__(self, E, G, n_nd, n_md):
        self.E = E
        self.G = G
        self.n_nd = n_nd
        self.n_md = n_md
        self.n_elem = self.n_nd - 1
        self.K_fl = [None]
        self.M_fl = [None]
        self.eigval = [None]
        self.PI = [None]
        self.PI_end = [None]
    
    def set_PI(self, PI):
        self.PI = PI
    
    def set_K_fl(self, K_fl):
        self.K_fl = K_fl

    def set_M_fl(self, M_fl):
        self.M_fl = M_fl

# END Body_Properties.py


# ==============================================================================
# BEGIN Structural_Analysis_PM_Rect.py
# ==============================================================================

import numpy as np
import scipy.linalg as la
import pandas as pd
from SOALIB import soalib as sb
# from Body_Properties import Rigid_Properties, Flex_Properties  # (merged into single file)


class Structural_Analysis_PM_Rect:
    """
    Class:
    Structural analysis of 3D rectangular cantilever beam with point mass assumption.

    Call:
    Structural_Analysis_PM_Rect(klOO, rho, E, G, n_nd, n_md)

    Constraint:
    Width, w >= Height, h
    """

    def get_stiff_mat_rect_3D(self):
        # b < a // h < w, w = y, h = z
        # Parameters
        w = self.w
        h = self.h
        a = w / 2
        b = h / 2
        L = self.L_elem
        E = self.E
        G = self.G

        # Book -> code
        # x -> z
        # y -> x
        # z -> y

        # Rectangular cross-section
        k_y = 1.2
        k_z = k_y
        K = a * b**3 * (16/3 - 3.36 * a / b * (1 - a**4 / (12 * b**4)))
        A = self.A
        I_y = w * h**3 / 12
        I_z = h * w**3 / 12

        # Factors
        phi_y = 12 * E * I_z * k_y / (A * G * L**2)
        phi_z = 12 * E * I_y * k_z / (A * G * L**2)
        S = G * K / L

        # X
        X = A * E / L

        # Y
        Y_1 = 12 * E * I_z / ((1 + phi_y) * L**3)
        Y_2 = 6 * E * I_z / ((1 + phi_y) * L**2)
        Y_3 = (4 + phi_y) * E * I_z / ((1 + phi_y) * L)
        Y_4 = (2 - phi_y) * E * I_z / ((1 + phi_y) * L)

        # Z
        Z_1 = 12 * E * I_y / ((1 + phi_z) * L**3)
        Z_2 = 6 * E * I_y / ((1 + phi_z) * L**2)
        Z_3 = (4 + phi_z) * E * I_y / ((1 + phi_z) * L)
        Z_4 = (2 - phi_z) * E * I_y / ((1 + phi_z) * L)

        # Stiffness matrix
        diag = [None] * 6

        diag[0] = np.array(
            [X, Y_1, Z_1, S, Z_3, Y_3, X, Y_1, Z_1, S, Z_3, Y_3])
        diag[1] = np.array([0, 0, -Z_2, 0, 0, -Y_2, 0, 0, Z_2, 0])
        diag[2] = np.array([0, Y_2, 0, 0, Z_2, 0, 0, -Y_2])
        diag[3] = np.array([-X, -Y_1, -Z_1, -S, Z_4, Y_4])
        diag[4] = np.array([0, 0, -Z_2, 0])
        diag[5] = np.array([0, Y_2])

        k = np.diag(diag[0], k=0)

        for i in range(1, 6):
            k = k + np.diag(diag[i], k=-2*i) + np.diag(diag[i], k=2*i)

        # Change so rotations first is along
        perm = [3, 4, 5, 0, 1, 2, 9, 10, 11, 6, 7, 8]

        k_perm = k[np.ix_(perm, perm)]

        return k_perm

    def get_K_st(self):

        # Get nodal stiffness
        k = self.get_stiff_mat_rect_3D()

        # Global stiffness matrix setup
        K_st = np.zeros((6*self.n_nd, 6*self.n_nd))

        for i in range(self.n_nd - 1):
            k_i = np.zeros((6*self.n_nd, 6*self.n_nd))
            k_i[i*6:i*6+12, i*6:i*6+12] = k
            K_st = K_st + k_i

        return K_st

    def get_M_nd(self):
        # Nodal masses
        m_e = self.m_e

        m = np.full(self.n_nd, m_e)
        m[-1], m[0] = m_e / 2, m_e / 2

        # Store nodal masses and lenghts
        self.m_nd = m

        block = []
        for i in range(self.n_nd):
            block.append(np.zeros((3, 3)))
            block.append(m[i] * np.eye(3, 3))

        M = la.block_diag(*block)

        return M

    def get_PI(self):

        # Fixed BC
        K_st = self.K_st[6:, 6:]
        M_nd = self.M_nd[6:, 6:]

        # Rearranging of M and K
        index = np.zeros((1, 0))

        for i in range(self.n_elem):
            index_add = np.linspace(i * 6 + 3, i * 6 + 5, 3).reshape(1, 3)
            index = np.hstack([index, index_add])

        for i in range(self.n_elem):
            index_add = np.linspace(i * 6, i * 6 + 2, 3).reshape(1, 3)
            index = np.hstack([index, index_add])

        index = index.flatten().astype(int)
        K = K_st[np.ix_(index, index)]
        M = M_nd[np.ix_(index, index)]

        # Find K_tt, K_rr, K_tr, K_rt and M_c
        sz = M.shape[0]
        sz2 = int(sz / 2)

        K_tt = K[0:sz2, 0:sz2]
        K_rr = K[sz2:sz, sz2:sz]
        K_tr = K[0:sz2, sz2:sz]
        K_rt = K[sz2:sz, 0:sz2]

        M_c = M[0:sz2, 0:sz2]

        # Find K_e (np.linalg.inv(K_rr) * K_rt)
        X = la.solve(K_rr, K_rt, assume_a="sym")
        K_c = K_tt - K_tr @ X

        # Solve eigenvalue problem for Pi_t (Mass normalized!)
        eigval, PI_t = la.eigh(K_c, M_c, subset_by_index=(0, self.n_md - 1))

        # Store eigen values
        self.eigval = eigval

        # Compute rotational part of PI
        PI_r = - X @ PI_t

        # Store PI_r and PI_t for modal integrals
        self.PI_r = np.vstack([np.zeros((3, self.n_md)), PI_r])
        self.PI_t = np.vstack([np.zeros((3, self.n_md)), PI_t])

        # PI setup
        PI = np.zeros((2 * PI_t.shape[0] + 6, PI_t.shape[1]))
        for i in range(self.n_elem):
            PI[i * 6 + 6:i * 6 + 9, :] = PI_r[i * 3:i * 3 + 3, :]
            PI[i * 6 + 9:i * 6 + 12, :] = PI_t[i * 3:i * 3 + 3, :]

        return PI

    def get_K_fl(self):
        # Initialize K
        K = np.zeros((self.n_md + 6, self.n_md + 6))
        K[0:self.n_md, 0:self.n_md] = self.PI.T @ self.K_st @ self.PI

        return K

    def get_Modal_Int(self):
        # Parameters
        m = self.m
        m_nd = self.m_nd.reshape(-1, 1)
        L_elem = self.L_elem
        PI_t = self.PI_t
        n_md = self.n_md
        n_nd = self.n_nd

        # Initialize sums
        p_0_sum = np.zeros((3, 1))
        p_1_sum = np.zeros((3, n_md))
        CkJk_0_sum = np.zeros((3, 3))
        CkJk_1_sum = np.zeros((3, 3*n_md))
        CkJk_2_sum = np.zeros((3*n_md, 3*n_md))
        F_0_sum = np.zeros((3, n_md))
        F_1_sum = np.zeros((3*n_md, n_md))
        G_0_sum = np.zeros((n_md, n_md))
        E_0_sum = np.zeros((3, n_md))

        for i in range(n_nd):
            # Parameters
            klkO = np.array([i * L_elem, 0, 0]).reshape(3, 1)
            klkO_skew = sb.skew(klkO)

            # Compute sums
            p_0_sum += m_nd[i] * klkO

            CkJk_0_sum += - m_nd[i] * klkO_skew @ klkO_skew

            for r in range(n_md):
                F_0_sum[:, r] += m_nd[i] * \
                    klkO_skew @ PI_t[i * 3: i * 3 + 3, r]
                E_0_sum[:, r] += m_nd[i] * PI_t[i * 3: i*3 + 3, r]
                p_1_sum[:, r] += m_nd[i] * PI_t[i * 3: i*3 + 3, r]
                CkJk_1_sum[:, 3 * r: 3 * r + 3] += m_nd[i] * \
                    sb.skew(PI_t[i * 3: i*3 + 3, r]) @ klkO_skew
                for s in range(n_md):
                    G_0_sum[r, s] += m_nd[i] * PI_t[i * 3: i *
                                                    3 + 3, r].T @ PI_t[i * 3: i*3 + 3, s]
                    CkJk_2_sum[3*r:3*r+3, 3*s:3*s+3] += m_nd[i] * sb.skew(PI_t[i * 3: i *
                                                                               3 + 3, r]) @ sb.skew(PI_t[i * 3: i*3 + 3, s])
                    F_1_sum[3*r:3*r+3, s] += m_nd[i] * sb.skew(PI_t[i * 3: i *
                                                                    3 + 3, r]) @ PI_t[i * 3: i*3 + 3, s]

        # Store modal integrals
        self.p_0 = 1/m * p_0_sum
        self.p_1 = 1/m * p_1_sum
        self.CkJk_0 = CkJk_0_sum
        self.CkJk_0[2, 2] = self.CkJk[2]
        self.CkJk_1 = - CkJk_1_sum
        self.CkJk_2 = - CkJk_2_sum
        self.F_0 = F_0_sum
        self.F_1 = - F_1_sum
        self.G_0 = G_0_sum
        self.E_0 = E_0_sum

    def get_M_fl(self):
        # Collect modal integrals
        self.get_Modal_Int()

        # Parameters
        p_0_skew = sb.skew(self.p_0)
        CkJk_0 = self.CkJk_0
        F_0 = self.F_0
        G_0 = self.G_0
        E_0 = self.E_0

        m = self.m

        # Build M
        rw1 = np.hstack([G_0, F_0.T, E_0.T])
        rw2 = np.hstack([F_0, CkJk_0, m * p_0_skew])
        rw3 = np.hstack([E_0, -m * p_0_skew, m * np.eye(3)])

        return np.vstack([rw1, rw2, rw3])

    def __init__(self, rigid: Rigid_Properties, flex: Flex_Properties):
        self.w = rigid.w
        self.h = rigid.h
        self.L = rigid.L
        self.A = rigid.w * rigid.h
        self.m = rigid.rho * self.A * self.L
        self.E = flex.E
        self.G = flex.G
        self.n_nd = flex.n_nd
        self.n_md = flex.n_md
        self.CkJk = rigid.CkJk
        self.n_elem = self.n_nd - 1
        self.L_elem = self.L / self.n_elem
        self.m_e = rigid.rho * self.A * self.L_elem

        # Structural analysis
        self.K_st = self.get_K_st()
        self.M_nd = self.get_M_nd()
        self.PI = self.get_PI()
        self.K_fl = self.get_K_fl()
        self.M_fl = self.get_M_fl()

# END Structural_Analysis_PM_Rect.py


# ==============================================================================
# BEGIN SystemState.py
# ==============================================================================

import numpy as np
import pandas as pd

class SystemState:
# State of system class
    def __init__(self, theta, beta, eta, eta_dot):
        # Parameters
        self.Theta = theta
        self.Beta = beta
        self.Eta = eta
        self.Eta_dot = eta_dot

    # Packing of state, S: Four lists to column vector
    def pack(self):
        return np.vstack([*self.Theta, *self.Beta, *self.Eta, *self.Eta_dot]).flatten()

    # Unpacking of state, S: Column vector to two lists
    @staticmethod
    def unpack(S, joints, flexs):
        S = S.flatten()
        Theta, Beta, Eta, Eta_dot = [], [], [], []
        idx = 0

        for k in joints:
            sz = k.theta_size()
            Theta.append(S[idx:idx + sz].reshape(sz, 1))
            idx += sz

        for k in joints:
            sz = k.beta_size()
            Beta.append(S[idx:idx + sz].reshape(sz, 1))
            idx += sz

        for k in flexs:
            sz = k.n_md
            Eta.append(S[idx:idx + sz].reshape(sz, 1))
            idx += sz
        
        for k in flexs:
            sz = k.n_md
            Eta_dot.append(S[idx:idx + sz].reshape(sz, 1))
            idx += sz

        return SystemState(Theta, Beta, Eta, Eta_dot)

# END SystemState.py


# ==============================================================================
# BEGIN ATBI_Flex.py
# ==============================================================================

import numpy as np
import scipy.linalg as la
from SOALIB import soalib as sb
# from SystemState import SystemState  # (merged into single file)
import pandas as pd


class ATBI_Flex:
    # ATBI class with bodies
    def __init__(self, bodies):
        # Parameters
        self.bodies = bodies
        self.n = len(bodies)

    def coriolis(self, V, beta, H):
        deltaV = H.T @ beta
        return sb.skew6(V) @ deltaV - sb.bar6(deltaV) @ deltaV

    def gyroscopic(self, V, M):
        return sb.bar6(V) @ M @ V

    def theta2X(self, theta, joint_type, klOO):
        if joint_type == "revx":
            ang = theta.item()
            q = np.array([[np.sin(ang/2)], [0], [0], [np.cos(ang/2)]])
            return np.vstack((q, klOO)), q

        elif joint_type == "revy":
            ang = theta.item()
            q = np.array([[0], [np.sin(ang/2)], [0], [np.cos(ang/2)]])
            return np.vstack((q, klOO)), q

        elif joint_type == "revz":
            ang = theta.item()
            q = np.array([[0], [0], [np.sin(ang/2)], [np.cos(ang/2)]])
            return np.vstack((q, klOO)), q

        elif joint_type == "spherical":
            q = theta.reshape(4, 1)
            return np.vstack((q, klOO)), q

        elif joint_type == "free":
            q = theta[0:4].reshape(4, 1)
            v = theta[4:7].reshape(3, 1)
            return np.vstack((q, klOO)), q

        elif joint_type == "fixed":
            q = np.array([[0], [0], [0], [1]])
            return np.vstack((q, klOO)), q

    def scatter_kinematics(self, state: SystemState):

        # Number of bodies
        n = len(self.bodies)

        # Set up lists
        X = [None] * n
        V = [None] * n
        A_fl = [None] * n
        V_f = [None] * n
        V_r = [None] * n
        a_fl = [None] * n
        b_fl = [None] * n

        for k in reversed(range(n)):
            # Parameters of the body
            body = self.bodies[k]
            theta = state.Theta[k]
            beta = state.Beta[k]
            eta_dot = state.Eta_dot[k]
            H = body.joint.H
            Mk = body.rigid.Mk
            PI = body.flex.PI_end
            n_md = body.flex.n_md

            # Build X
            X[k], q = self.theta2X(theta, body.joint.type, body.joint.klOO)

            # Build A: NB! Typo in text?!?!
            R3 = sb.q2R(q.flatten(), 3)
            A_fl[k] = sb.get_A(PI, R3.T @ X[k][4:7])

            if k == n - 1:
                V_f[k] = eta_dot
                V_r[k] = H.T @ beta
            else:
                R6 = sb.q2R(q.flatten(), 6)
                R_tot = sb.get_R_tot(R6, n_md)

                V_f[k] = eta_dot
                V_r[k] = A_fl[k+1].T @ R_tot.T @ V[k+1] + H.T @ beta

            a_fl[k] = np.vstack(
                [np.zeros((n_md, 1)), self.coriolis(V_r[k], beta, H)])
            b_fl[k] = np.vstack(
                [np.zeros((n_md, 1)), self.gyroscopic(V_r[k], Mk)])

            V[k] = np.vstack([V_f[k], V_r[k]])

        return X, V, a_fl, b_fl

    def gather_ATBI(self, state: SystemState, a_fl, b_fl, X, t):
        # Step 3 of ATBI (gather sweep): Takes generalized forces, Coriolis-, gyroscopic
        # terms, X-vector and system configuration and returns G and nu parameters

        # Number of bodies
        n = len(self.bodies)

        # Setup lists
        P_pr_plus = [None] * n
        D_m = [None] * n
        g_fl = [None] * n
        P_pr = [None] * n
        D_pr = [None] * n
        G_pr = [None] * n
        nu_m = [None] * n
        nu_pr = [None] * n
        z_pr_plus = [None] * n

        for k in range(n):
            # Parameters of the body
            body = self.bodies[k]
            H_B = body.joint.H
            F_ext = body.force.F_ext
            tau_pr = body.force.tau
            eta = state.Eta[k]
            M_fl = body.flex.M_fl
            K_fl = body.flex.K_fl
            PI = body.flex.PI_end
            n_md = body.flex.n_md
            H_M_fl = np.hstack([np.eye(n_md, n_md), np.zeros((n_md, 6))])
            klOO = X[k][4:7]

            # External force
            F_ext_term = np.zeros((b_fl[k].shape[0], 1))

            if t <= 0.25:
                F_ext_term = np.vstack([PI.T @ F_ext, sb.phi(klOO) @ F_ext])

            if k == 0:
                # Gather loop for k = 0 (Base Case)
                # 13.6
                Gamma_fl = np.zeros((0, 6))
                P_fl = M_fl
                D_m[k] = H_M_fl @ P_fl @ H_M_fl.T
                mu_fl = P_fl[-6:, :] @ H_M_fl.T
                D_m_inv = body.get_D_m_inv(Gamma_fl, 0)
                g_fl[k] = mu_fl @ D_m_inv
                P_pr[k] = P_fl[-6:, -6:] - g_fl[k] @ mu_fl.T
                D_pr[k] = H_B @ P_pr[k] @ H_B.T
                G_pr[k] = P_pr[k] @ la.solve(D_pr[k].T, H_B).T
                tau_pr_bar = np.eye(6, 6) - G_pr[k] @ H_B
                P_pr_plus[k] = tau_pr_bar @ P_pr[k]

                # 13.7
                z = b_fl[k] + \
                    K_fl @ np.vstack([eta, np.zeros((6, 1))]) - F_ext_term
                eps_m = - z[0:n_md]  # tau_m (assumed to be zero): dim(n_md, 1)
                nu_m[k] = D_m_inv @ eps_m

                z_pr = z[-6:] + g_fl[k] @ eps_m + P_pr[k] @ a_fl[k][-6:]
                eps_pr = tau_pr - H_B @ z_pr
                nu_pr[k] = la.solve(D_pr[k], eps_pr)
                z_pr_plus[k] = z_pr + G_pr[k] @ eps_pr

            else:
                # 13.6
                # Unpacking X-vector
                q = X[k-1][0:4]

                # Rotation
                R6 = sb.q2R(q.flatten(), 6)

                A_fl = sb.get_A(PI, klOO)

                # Gather loop for k > 0
                Gamma_fl = R6 @ P_pr_plus[k-1] @ R6.T  # ?!?!?!?
                P_fl = A_fl @ Gamma_fl @ A_fl.T + M_fl
                D_m[k] = H_M_fl @ P_fl @ H_M_fl.T
                mu_fl = P_fl[-6:, :] @ H_M_fl.T
                D_m_inv = body.get_D_m_inv(Gamma_fl, 1)
                g_fl[k] = mu_fl @ D_m_inv
                P_pr[k] = P_fl[-6:, -6:] - g_fl[k] @ mu_fl.T
                D_pr[k] = H_B @ P_pr[k] @ H_B.T
                G_pr[k] = P_pr[k] @ la.solve(D_pr[k].T, H_B).T
                tau_pr_bar = np.eye(6, 6) - G_pr[k] @ H_B
                P_pr_plus[k] = tau_pr_bar @ P_pr[k]

                # 13.7
                z = A_fl @ R6 @ z_pr_plus[k-1] + b_fl[k] + \
                    K_fl @ np.vstack([eta, np.zeros((6, 1))]) - F_ext_term
                eps_m = - z[0:n_md]  # tau_m (assumed to be zero): dim(n_md, 1)
                nu_m[k] = D_m_inv @ eps_m

                z_pr = z[-6:] + g_fl[k] @ eps_m + P_pr[k] @ a_fl[k][-6:]
                eps_pr = tau_pr - H_B @ z_pr
                nu_pr[k] = la.solve(D_pr[k], eps_pr)
                z_pr_plus[k] = z_pr + G_pr[k] @ eps_pr

        return G_pr, nu_pr, nu_m, g_fl

    def scatter_ATBI(self, a_fl, X, G_pr, nu_pr, nu_m, g_fl):
        # Step 4 of ATBI (second scatter sweep): Takes Coriolis term, X-vector, G,
        # nu and hinge map, H and returns generalized acceleration, gamma

        # Number of bodies
        n = len(self.bodies)

        # Setup of list
        alpha_fl = [None] * n
        theta_ddot = [None] * n
        eta_ddot = [None] * n
        A_fl = [None] * n

        # Spatial gravity
        g = np.array([0, 0, 0, 0, 0, 9.81]).reshape(6, 1)

        # Spatial gravity rotation setup
        Ri = [None] * (n + 1)
        Ri[-1] = np.eye(6)

        # Loop backwards from n-1 down to 0
        for k in range(n - 1, -1, -1):
            # Parameters of the body
            body = self.bodies[k]
            H_B = body.joint.H
            n_md = body.flex.n_md
            PI = body.flex.PI_end

            # Unpacking rotation
            q = X[k][0:4]

            # Rotation
            R3 = sb.q2R(q.flatten(), 3)
            R6 = sb.q2R(q.flatten(), 6)

            # Spatial gravity rotation
            Ri[k] = Ri[k+1]  @ R6

            A_fl[k] = sb.get_A(PI, R3.T @ X[k][4:7])

            if k == n - 1:
                # Scatter loop (Tip of the chain)
                theta_ddot[k] = nu_pr[k]
                alpha_pr = H_B.T @ theta_ddot[k] + a_fl[k][-6:]
                eta_ddot[k] = nu_m[k] - g_fl[k].T @ alpha_pr
                alpha_fl[k] = np.vstack([eta_ddot[k], alpha_pr])

            else:
                # Scatter loop
                R_tot = sb.get_R_tot(R6, n_md)

                alpha_pr_plus = A_fl[k+1].T @ R_tot.T @ alpha_fl[k+1]
                theta_ddot[k] = nu_pr[k] - G_pr[k].T @ alpha_pr_plus
                alpha_pr = alpha_pr_plus + H_B.T @ theta_ddot[k] + a_fl[k][-6:]
                eta_ddot[k] = nu_m[k] - g_fl[k].T @ alpha_pr
                alpha_fl[k] = np.vstack([eta_ddot[k], alpha_pr])

        return theta_ddot, eta_ddot, alpha_fl

# END ATBI_Flex.py


# ==============================================================================
# BEGIN MultibodySystem.py
# ==============================================================================

import numpy as np
import pandas as pd
from SOALIB import soalib as sb
# from SystemState import SystemState  # (merged into single file)
# from ATBI_Flex import ATBI_Flex  # (merged into single file)


class MultibodySystem:
    def __init__(self, bodies):
        self.bodies = bodies
        self.ATBI = ATBI_Flex(bodies)
        Theta_0 = [b.initialcondition.theta0 for b in bodies]
        Beta_0 = [b.initialcondition.beta0 for b in bodies]
        Eta_0 = [b.initialcondition.eta0 for b in bodies]
        Eta_dot_0 = [b.initialcondition.eta_dot0 for b in bodies]
        self.S0 = SystemState(Theta_0, Beta_0, Eta_0, Eta_dot_0).pack()

    def EOM(self, t, S):
        state = SystemState.unpack(S.reshape(-1, 1), [b.joint for b in self.bodies], [b.flex for b in self.bodies])

        # Normalize quaternions
        for k, body in enumerate(self.bodies):
            if body.joint.type in ["spherical", "free"]:
                q = state.Theta[k][0:4]
                state.Theta[k][0:4] = q / np.linalg.norm(q)

        X, V, a_fl, b_fl = self.ATBI.scatter_kinematics(state)
        G_pr, nu_pr, nu_m, g_fl = self.ATBI.gather_ATBI(state, a_fl, b_fl, X, t)
        theta_ddot, eta_ddot, alpha_fl = self.ATBI.scatter_ATBI(a_fl, X, G_pr, nu_pr, nu_m, g_fl)

        Theta_dot, Eta_dot_list = [], []
        for k, body in enumerate(self.bodies):
            if body.joint.type.startswith("rev"):
                Theta_dot.append(state.Beta[k].reshape(1, 1))
            elif body.joint.type == "spherical":
                Theta_dot.append(sb.quat_derivative(state.Theta[k], state.Beta[k]).reshape(4, 1))
            elif body.joint.type == "free":
                qdot = sb.quat_derivative(state.Theta[k][0:4], state.Beta[k][0:3]).reshape(4, 1)
                Theta_dot.append(np.vstack([qdot, state.Beta[k][3:6]]).reshape(7, 1))
            elif body.joint.type == "fixed":
                Theta_dot.append(np.zeros((0, 1)))

            Eta_dot_list.append(state.Eta_dot[k].reshape(body.flex.n_md, 1))

        S_dot = np.vstack([*Theta_dot, *theta_ddot, *Eta_dot_list, *eta_ddot]).flatten()
        
        return S_dot

# END MultibodySystem.py


# ==============================================================================
# BEGIN Simulation.py
# ==============================================================================

import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
from matplotlib.animation import FuncAnimation
from scipy.integrate import solve_ivp
import os
# from MultibodySystem import MultibodySystem  # (merged into single file)
# from SystemState import SystemState  # (merged into single file)
from SOALIB import soalib as sb
import pandas as pd


class Simulation:
    class Data:
        def __init__(self):
            self.time, self.state, self.X_list, self.V_list, self.a_list, self.b_list, self.alpha_list, self.pos = [
            ], [], [], [], [], [], [], []

    class Setting:
        def __init__(self):
            self.camera_speed = 0
            self.camera_ver = 20
            self.camera_hor = 0

    def __init__(self, system: MultibodySystem, tf, dt):
        self.system = system
        self.data = self.Data()
        self.setting = self.Setting()
        self.tf = tf
        self.dt = dt

        # Increase limit to 100 MB (default is 20)
        plt.rcParams['animation.embed_limit'] = 1000

    def IntegrateSystem(self):
        t_eval = np.linspace(0, self.tf, int(self.tf/self.dt)+1)

        sol = solve_ivp(
            fun=self.system.EOM,
            t_span=(0, self.tf),
            y0=self.system.S0,
            t_eval=t_eval,
            method="RK45",
        )

        print("Integration successful!")

        # Extract results to match [t, y] format
        self.data.time = sol.t
        states = sol.y.T

        # Find X-vector for each time step
        for i in range(len(self.data.time)):

            # Unpack state
            current_state = SystemState.unpack(
                states[i].reshape(-1, 1), [b.joint for b in self.system.bodies], [b.flex for b in self.system.bodies])

            # Kinematic scatter loop to find X
            X, V, a_fl, b_fl = self.system.ATBI.scatter_kinematics(
                current_state)
            G_pr, nu_pr, nu_m, g_fl = self.system.ATBI.gather_ATBI(
                current_state, a_fl, b_fl, X, self.data.time[i])
            _, _, alpha = self.system.ATBI.scatter_ATBI(
                a_fl, X, G_pr, nu_pr, nu_m, g_fl)

            # Add to list
            self.data.state.append(current_state)
            self.data.X_list.append(X)
            self.data.V_list.append(V)
            self.data.a_list.append(a_fl)
            self.data.b_list.append(b_fl)
            self.data.alpha_list.append(alpha)

    # Call functions for data
    def get_state(self):
        return self.data.state

    def get_X(self):
        return self.data.X_list

    def get_V(self):
        return self.data.V_list

    def get_a(self):
        return self.data.a_list

    def get_b(self):
        return self.data.b_list

    def get_alpha(self):
        return self.data.alpha_list

    # Settings
    def camera_speed(self, x):
        self.setting.camera_speed = x

    def camera_ver(self, x):
        self.setting.camera_ver = x

    def camera_hor(self, x):
        self.setting.camera_hor = x

    def nNodalPos(self):
        t = self.data.time
        X = self.data.X_list

        # Access body 1 (index 0) parameters
        body = self.system.bodies[0]
        n_nd = body.flex.n_nd
        PI = body.flex.PI
        L = body.rigid.L
        L_elem = L / (n_nd - 1)

        nt = len(t)
        nodal_pos = []

        for i in range(nt):
            state = self.data.state[i]
            eta = state.Eta[0]

            # Base translation (account for free joint if applicable)
            dxyz = np.zeros((3, 1))
            if body.joint.type == "free":
                dxyz = state.Theta[0][4:7].reshape(3, 1)

            nodes_at_t = []

            for j in range(n_nd):
                # 1. Undeformed position in local frame (Structural analysis assumes beam along Z-axis)
                p_und = np.array([[j * L_elem], [0], [0]])

                # 2. Translational deformation for node j
                # (Translations are stored at indices j*6+3 to j*6+6 in the PI matrix)
                # Define a small tolerance based on your dt
                tolerance = 1e-6

                # Check if the current time is very close to an integer
                x = 0
                if i % 20 == 0 and j == n_nd-1 and x == 1:
                    print(pd.DataFrame(eta))
                    print(pd.DataFrame(PI[j*6+3: j*6+6, :]))

                u_j = PI[j*6+3: j*6+6, :] @ eta

                # 3. Global position of node j
                p_glob = dxyz + (p_und + u_j)
                nodes_at_t.append(p_glob)

            nodal_pos.append(nodes_at_t)

        return nodal_pos

    def animate_nodes(self, filename="", save_dir=""):
        # Takes nodal position list and returns 3D simulation of the flexible beam

        t = self.data.time
        dt = t[1] - t[0]

        # Get nodal positions for the flexible beam
        nodal_pos = self.nNodalPos()

        if not nodal_pos:
            print("Error: No nodal position data found. Did you run the integration?")
            return

        nt = len(nodal_pos)
        n_nd = len(nodal_pos[0])

        # Initialize animation
        fig = plt.figure(figsize=(10, 8))
        ax = fig.add_subplot(111, projection='3d')

        # Determine Axis Limits dynamically based on node movement
        all_points = []
        # Sample frames to speed up boundary calculation
        step = max(1, nt // 50)
        for i in range(0, nt, step):
            for node in nodal_pos[i]:
                all_points.append(node.flatten())

        all_points = np.array(all_points)
        max_range = np.abs(all_points).max()

        # Prevent zero-range if the beam doesn't move
        if max_range == 0:
            max_range = 1.0

        ax.set_xlim(-2, 7)
        ax.set_ylim(-2, 2)
        ax.set_zlim(-2, 2)

        ax.set_xlabel('X')
        ax.set_ylabel('Y')
        ax.set_zlabel('Z')
        ax.set_title(f"Flexible Beam Animation ({n_nd} Nodes)")

        # Create a single line representing the continuous flexible beam
        beam_line, = ax.plot([], [], [], '-', lw=4,
                             color='blue', marker='o', markersize=4)

        # Plot origin for reference
        ax.plot([0], [0], [0], 'o', color='gray', markersize=6)

        # Initialize the timer text
        time_text = ax.text2D(0.05, 0.95, '', transform=ax.transAxes)

        def update(frame_idx):
            current_nodes = nodal_pos[frame_idx]

            # Extract x, y, z coordinates for all nodes at the current frame
            xs = [float(node[0][0]) for node in current_nodes]
            ys = [float(node[1][0]) for node in current_nodes]
            zs = [float(node[2][0]) for node in current_nodes]

            # Update the beam line data
            beam_line.set_data(xs, ys)
            beam_line.set_3d_properties(zs)

            # Update timer
            time_text.set_text(f'Time: {t[frame_idx]:.2f} s')

            # Handle camera rotation settings
            ax.view_init(elev=self.setting.camera_ver,
                         azim=frame_idx * self.setting.camera_speed * 40 * dt + self.setting.camera_hor)

            return beam_line, time_text

        # Create Animation
        anim = FuncAnimation(
            fig,
            update,
            frames=nt,
            interval=dt*1000,
            blit=False)

        if filename != "":
            print("Rendering animation to HTML... (This may take a minute)")
            filename = filename + ".html"

            if save_dir:
                os.makedirs(save_dir, exist_ok=True)
                fullpath = os.path.join(save_dir, filename)
            else:
                fullpath = filename

            with open(fullpath, "w") as f:
                f.write(anim.to_jshtml())

            print("Rendering of animation: Done!")
            print(f"Saved to {fullpath}")

        else:
            plt.show()

    def nBodyPos(self):
        # Takes time vector, t and X-vector [q, klOO]^T and returns hinge positions

        t = self.data.time
        X = self.data.X_list
        klOO_B = [b.joint.klOO for b in self.system.bodies]

        # Number of bodies and time steps
        n = len(X[0])
        nt = len(t)

        # Setup hinge position list
        penPos = []

        dxyz = np.zeros((3, 1))

        for i in range(nt):
            # Account for possible free BASE hinge
            if self.system.bodies[-1].joint.type == "free":
                theta_base_free = self.data.state[i].Theta[-1]
                dxyz = theta_base_free[4:7]

            kpos = [None] * (n + 1)

            kpos[n] = np.zeros((3, 1))
            Ri = np.eye(3)

            for k in range(n - 1, -1, -1):
                # Unpancking X-vector
                q = X[i][k][0:4]    # Quaternion: k+1 to k
                klOO = X[i][k][4:7]  # O_k to O_k-1^+

                # Rotation
                Ri = Ri @ sb.q2R(q.flatten(), 3)

                # Hinge position
                kpos[k] = kpos[k+1] + Ri @ klOO

            # Rotation of base body k = -1
            q = X[i][-1][0:4]
            R_base = sb.q2R(q.flatten(), 3)

            # This will account for "free" base body hinge
            kpos[-1] = kpos[-2] - R_base @ klOO_B[-1]

            # Add to pendulum position list, penPos
            kpos = kpos - dxyz
            penPos.append(kpos)

        return penPos

    def get_pos(self):
        self.data.pos = self.nBodyPos()
        return self.data.pos

    def animate(self, filename="", save_dir=""):
        # Takes X-vector list and returns simulation

        t = self.data.time
        X = self.data.X_list

        # Number of bodies
        n = len(X[0])

        # Number of time steps and dt
        nt = len(t)
        dt = t[1] - t[0]

        # Get position for each time step
        penPos = self.nBodyPos()

        # Initialize animation
        fig = plt.figure(figsize=(10, 8))
        ax = fig.add_subplot(111, projection='3d')

        # Determine Axis Limits
        all_points = []

        for i in range(0, nt, 10):  # Sample every 10th frame for speed
            for body in penPos[i]:
                all_points.append(body.flatten())  # Flatten (3,1) to (3,)

        all_points = np.array(all_points)
        max_range = np.abs(all_points).max()
        ax.set_xlim(-max_range, max_range)
        ax.set_ylim(-max_range, max_range)
        ax.set_zlim(-max_range, 0)

        ax.set_xlabel('X')
        ax.set_ylabel('Y')
        ax.set_zlabel('Z')
        ax.set_title(f"n-Body Pendulum with ({len(penPos[0]) - 1} Bodies)")

        # Create n colored lines (one per link)
        cmap = mpl.colormaps['tab10']
        colors = cmap(np.linspace(0, 1, n))
        lines = []

        for i in range(n):
            line, = ax.plot([], [], [], '-', lw=4,
                            markersize=4, color=colors[i])
            lines.append(line)

        joint_dots, = ax.plot([], [], [], 'ko', markersize=4)

        ax.plot([0], [0], [0], 'o', color='gray', markersize=6)

        # Initialize the timer text (placed in top-left corner)
        time_text = ax.text2D(0.05, 0.95, '', transform=ax.transAxes)

        def update(frame_idx):
            current_state = penPos[frame_idx]

            # Extract joint positions
            xs = [float(body[0][0]) for body in current_state]
            ys = [float(body[1][0]) for body in current_state]
            zs = [float(body[2][0]) for body in current_state]

            # Update each link separately
            for i in range(n):
                lines[i].set_data(xs[i:i+2], ys[i:i+2])
                lines[i].set_3d_properties(zs[i:i+2])

            joint_dots.set_data(xs, ys)
            joint_dots.set_3d_properties(zs)

            # Update timer
            time_text.set_text(f'Time: {t[frame_idx]:.2f} s')

            ax.view_init(elev=self.setting.camera_ver, azim=frame_idx *
                         self.setting.camera_speed * 40 * dt + self.setting.camera_hor)

            return (*lines, joint_dots, time_text)

        # Create Animation
        anim = FuncAnimation(
            fig,
            update,
            frames=len(penPos),
            interval=dt*1000,
            blit=False)

        if filename != "":
            print("Rendering animation to HTML... (This may take a minute)")

            filename = filename + ".html"

            # Use the 'html' writer
            os.makedirs(save_dir, exist_ok=True)

            fullpath = os.path.join(save_dir, filename)

            with open(fullpath, "w") as f:
                f.write(anim.to_jshtml())

            print("Renedering of animation: Done!")
            print(f"Saved to {fullpath}")

        else:
            plt.show()

# END Simulation.py


# ==============================================================================
# BEGIN SOABody.py
# ==============================================================================

import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
from SOALIB import soalib as sb
from scipy.integrate import solve_ivp
# from Structural_Analysis_PM_Rect import Structural_Analysis_PM_Rect  # (merged into single file)
# from Body_Properties import Joint, Rigid_Properties, Flex_Properties  # (merged into single file)
import pandas as pd

# Increase limit to 100 MB (default is 20)
plt.rcParams['animation.embed_limit'] = 1000


class SOABody:
    # SOAbody class
    class Force:
        def __init__(self, joint: Joint):
            self.tau = np.zeros((joint.beta_size(), 1))
            self.F_ext = np.zeros((6, 1))

    class InitialCondition:
        def __init__(self, joint: Joint, flex: Flex_Properties):
            # Setup of initial conditions (assumes identity rotation and no initial velocity)
            self.theta0 = np.zeros((joint.theta_size(), 1))
            if np.size(self.theta0) == 4:
                self.theta0[-1] = 1
            elif np.size(self.theta0) == 7:
                self.theta0[3] = 1
            self.beta0 = np.zeros((joint.beta_size(), 1))

            # Setup of initial conditions for eta and eta_dot
            self.eta0 = np.zeros((flex.n_md, 1))
            self.eta_dot0 = np.zeros((flex.n_md, 1))

    def __init__(self, joint: Joint, rigid: Rigid_Properties, flex: Flex_Properties):
        # Import classes
        self.joint = joint
        self.rigid = rigid
        self.flex = flex
        self.force = self.Force(self.joint)
        self.initialcondition = self.InitialCondition(joint, flex)
        rigid.A = rigid.h * rigid.w
        rigid.L = joint.L
        self.m = rigid.rho * rigid.A * joint.L
        self.rigid.CkJk = np.array([1/12 * self.m * (rigid.h**2 + rigid.w**2), 1/12 * self.m * (
            rigid.h**2 + joint.L**2), 1/12 * self.m * (rigid.w**2 + joint.L**2)])
        rigid.Mk = rigid.get_Mk(self.m, self.rigid.CkJk)

        # Structural analysis is PI == [None] (Point mass: Rectangular cross section)
        if self.flex.PI == [None]:
            body_analysis = Structural_Analysis_PM_Rect(rigid, flex)

            print("p_0")
            print(pd.DataFrame(body_analysis.p_0))
            print("p_1")
            print(pd.DataFrame(body_analysis.p_1))
            print("CkJk_0")
            print(pd.DataFrame(body_analysis.CkJk_0))
            print("CkJk_1")
            print(pd.DataFrame(body_analysis.CkJk_1))
            print("CkJk_2")
            print(pd.DataFrame(body_analysis.CkJk_2))
            print("F_0")
            print(pd.DataFrame(body_analysis.F_0))
            print("F_1")
            print(pd.DataFrame(body_analysis.F_1))
            print("G_0")
            print(pd.DataFrame(body_analysis.G_0))
            print("E_0")
            print(pd.DataFrame(body_analysis.E_0))
            print("eig")
            print(pd.DataFrame(body_analysis.eigval))
            print("PI_t")
            print(pd.DataFrame(body_analysis.PI_t))
            print("K_st")
            print(pd.DataFrame(body_analysis.K_st))

            # PI
            self.flex.PI = body_analysis.PI
            self.flex.PI_end = body_analysis.PI[-6:, :]
            self.flex.eigval = body_analysis.eigval

            # Stiffness and mass matrix
            self.flex.K_fl = body_analysis.K_fl
            self.flex.M_fl = body_analysis.M_fl

        # D_m invers (offline)
        H_M_fl = np.hstack(
            [np.eye(self.flex.n_md, self.flex.n_md), np.zeros((self.flex.n_md, 6))])
        A_fl = sb.get_A(self.flex.PI_end, self.joint.klOO)
        self.flex.L_fl = la.inv(H_M_fl @ self.flex.M_fl @ H_M_fl.T)
        zeta = H_M_fl @ A_fl
        self.flex.U_fl = self.flex.L_fl @ zeta
        self.flex.D_fl = zeta.T @ self.flex.U_fl

    def set_tau(self, tau):
        self.force.tau = tau

    def set_F_ext(self, F_ext):
        self.force.F_ext = F_ext

    def set_initial_theta0(self, theta0):
        self.initialcondition.theta0 = theta0

    def set_initial_beta0(self, beta0):
        self.initialcondition.beta0 = beta0

    def get_D_m_inv(self, Gamma, x):
        # Calculate D_m_inv
        if x == 0:
            Dminv = self.flex.L_fl
        elif x == 1:
            Gamma_inv = la.inv(Gamma)
            Dminv = self.flex.L_fl - \
                la.solve((Gamma_inv + self.flex.D_fl).T,
                         self.flex.U_fl.T).T @ self.flex.U_fl.T
        return Dminv

# END SOABody.py


# ==============================================================================
# BEGIN TestFlex.py
# ==============================================================================

if __name__ == '__main__':
    # from SOABody import SOABody  # (merged into single file)
    # from MultibodySystem import MultibodySystem  # (merged into single file)
    # from Simulation import Simulation  # (merged into single file)
    # from Body_Properties import Joint, Rigid_Properties, Flex_Properties  # (merged into single file)
    import numpy as np
    from SOALIB import soalib as sb
    import pandas as pd

    L = 5
    H_type1 = "revz"

    m = 1
    klOC = np.array([2.5, 0, 0])

    # n_md_max = (n_nd - 1) * 3

    E, G, rho, n_nd, n_md = 230e9, 80e9, 7850, 6, 5

    w, h = 0.1, 0.1

    j1 = Joint(L, H_type1)
    r = Rigid_Properties(rho, klOC, w, h)
    f = Flex_Properties(E, G, n_nd, n_md)
    b1 = SOABody(j1, r, f)

    PIe = b1.flex.PI_end

    K = b1.flex.K_fl
    M = b1.flex.M_fl

    F_ext = np.array([0, 0, 0, -1e5, 0, 0]).reshape(6, 1)
    b1.set_F_ext(F_ext)
    b1.set_initial_beta0(-2)

    bodies = [b1]

    system = MultibodySystem(bodies)

    tf = 10
    dt = 0.01

    sim = Simulation(system, tf, dt)

    # sim.camera_speed(0.5)
    sim.camera_ver(45)
    sim.camera_hor(0)

    sim.IntegrateSystem()

    save_dir = r"C:\Users\jepp6\OneDrive - Aarhus universitet\Dokumenter\Noter\6. Semester\Bachelor Projekt\BachelorCode\Renders"

    sim.animate_nodes()


    """
    print("PI")
    print(pd.DataFrame(b1.flex.PI))
    print("eigval")
    print(pd.DataFrame(b1.flex.eigval))
    print("K_fl")
    print(pd.DataFrame(b1.flex.K_fl))
    print("M_fl_red")
    print(pd.DataFrame(b1.flex.M_fl[-6:, -6:]))
    print("M_fl")
    print(pd.DataFrame(b1.flex.M_fl))
    """

# END TestFlex.py
